Repository RSS3-Network/Node, pull requests merged in 2024-06, with the labels that each got.

#373 feat(source/arweave): add irys graphql query support
  internal/engine/source/arweave/data_source.go
  internal/engine/source/arweave/filter.go
  internal/engine/source/arweave/state.go
  internal/engine/worker/contract/momoka/worker.go
  provider/arweave/bundle/irys/constant.go
  provider/arweave/bundle/irys/genqlient.yaml
  provider/arweave/bundle/irys/graphql.config.yaml
  provider/arweave/bundle/irys/operation.go
  provider/arweave/bundle/irys/operation/transactions.graphql
  provider/arweave/bundle/irys/operation_test.go
  provider/arweave/bundle/irys/schema.graphql
  provider/arweave/contract/momoka/contract.go
Labels: enhancement

#374 feat: farcaster index optimization
  internal/engine/source/farcaster/data_source.go
  internal/engine/worker/core/farcaster/worker.go
  internal/engine/worker/core/farcaster/worker_test.go
  provider/farcaster/client.go
  provider/farcaster/client_test.go
Labels: bug, enhancement

#389 feat: add related urls in social and collectible tag activities
  internal/node/component/decentralized/handler_activity.go
  internal/node/component/decentralized/transformer_activity.go
  internal/node/component/decentralized/transformer_collectible_type.go
  internal/node/component/decentralized/transformer_social_type.go
Labels: enhancement

#388 chore(makefile): add `make` commands for various Node services
  Makefile
Labels: priority/low, kind/developer-experience

#398 fix: add empty log check logic
  internal/engine/worker/decentralized/contract/curve/worker.go
  internal/engine/worker/decentralized/contract/curve/worker_test.go
  provider/ethereum/contract/curve/contract.go
Labels: kind/bug, priority/high, area/worker/curve

#397 refactor(worker): remove match from worker interface
  internal/engine/worker.go
  internal/engine/worker/decentralized/contract/1inch/worker.go
  internal/engine/worker/decentralized/contract/1inch/worker_test.go
  internal/engine/worker/decentralized/contract/aave/worker.go
  internal/engine/worker/decentralized/contract/aave/worker_test.go
  internal/engine/worker/decentralized/contract/aavegotchi/worker.go
  internal/engine/worker/decentralized/contract/aavegotchi/worker_test.go
  internal/engine/worker/decentralized/contract/crossbell/worker.go
  internal/engine/worker/decentralized/contract/crossbell/worker_test.go
  internal/engine/worker/decentralized/contract/curve/worker.go
  internal/engine/worker/decentralized/contract/curve/worker_test.go
  internal/engine/worker/decentralized/contract/ens/worker.go
  internal/engine/worker/decentralized/contract/ens/worker_test.go
  internal/engine/worker/decentralized/contract/highlight/worker.go
  internal/engine/worker/decentralized/contract/highlight/worker_test.go
  internal/engine/worker/decentralized/contract/iqwiki/worker.go
  internal/engine/worker/decentralized/contract/iqwiki/worker_test.go
  internal/engine/worker/decentralized/contract/kiwistand/worker.go
  internal/engine/worker/decentralized/contract/kiwistand/worker_test.go
  internal/engine/worker/decentralized/contract/lens/worker.go
  internal/engine/worker/decentralized/contract/lens/worker_test.go
  internal/engine/worker/decentralized/contract/lido/worker.go
  internal/engine/worker/decentralized/contract/lido/worker_test.go
  internal/engine/worker/decentralized/contract/looksrare/worker.go
  internal/engine/worker/decentralized/contract/looksrare/worker_test.go
  internal/engine/worker/decentralized/contract/matters/worker.go
  internal/engine/worker/decentralized/contract/matters/worker_test.go
  internal/engine/worker/decentralized/contract/mirror/worker.go
  internal/engine/worker/decentralized/contract/mirror/worker_test.go
  internal/engine/worker/decentralized/contract/momoka/worker.go
  internal/engine/worker/decentralized/contract/momoka/worker_test.go
  internal/engine/worker/decentralized/contract/opensea/worker.go
  internal/engine/worker/decentralized/contract/opensea/worker_test.go
  internal/engine/worker/decentralized/contract/optimism/worker.go
  internal/engine/worker/decentralized/contract/optimism/worker_test.go
  internal/engine/worker/decentralized/contract/paragraph/worker.go
  internal/engine/worker/decentralized/contract/paragraph/worker_test.go
  internal/engine/worker/decentralized/contract/rss3/worker.go
  internal/engine/worker/decentralized/contract/rss3/worker_test.go
  internal/engine/worker/decentralized/contract/savm/worker.go
  internal/engine/worker/decentralized/contract/savm/worker_test.go
  internal/engine/worker/decentralized/contract/stargate/worker.go
  internal/engine/worker/decentralized/contract/stargate/worker_test.go
  internal/engine/worker/decentralized/contract/uniswap/worker.go
  internal/engine/worker/decentralized/contract/uniswap/worker_test.go
  internal/engine/worker/decentralized/contract/vsl/worker.go
  internal/engine/worker/decentralized/contract/vsl/worker_test.go
  internal/engine/worker/decentralized/core/arweave/worker.go
  internal/engine/worker/decentralized/core/arweave/worker_test.go
  internal/engine/worker/decentralized/core/ethereum/worker.go
  internal/engine/worker/decentralized/core/ethereum/worker_test.go
  internal/engine/worker/decentralized/core/farcaster/worker.go
  internal/engine/worker/decentralized/core/farcaster/worker_test.go
  internal/node/indexer/server.go
Labels: area/worker, priority/low, kind/refactor
